---
- &copy_apt
  name: Copy apt module
  ansible.builtin.copy:
    src: "/usr/lib/python3/dist-packages/{{ item.src }}"
    dest: "{{ lookup('ansible.builtin.env', 'PYENV_VIRTUAL_ENV') }}/lib/\
      python{{ lookup('ansible.builtin.env', 'python_major_version') }}/site-packages/{{ item.dst }}"
    remote_src: true
    mode: preserve
  loop: "{{ python_files }}"

- name: Update system
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    cache_valid_time: 600
    upgrade: dist
  become: true

# this is not a mistake, the files may have changed after dist-upgrade
- *copy_apt

- name: Create python{{ lookup('ansible.builtin.env', 'python_major_version') }}
  ansible.builtin.command: pyenv virtualenv python{{ lookup('ansible.builtin.env', 'python_major_version') }}
  args:
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.pyenv/versions/{{ lookup('ansible.builtin.env', 'python_major_version') }}\
      /envs/python{{ lookup('ansible.builtin.env', 'python_major_version') }}"

- name: Install packages inside python{{ lookup('ansible.builtin.env', 'python_major_version') }}
  ansible.builtin.pip:
    name: "{{ python_pip_packages }}"
    virtualenv: "{{ lookup('ansible.builtin.env', 'HOME') }}/.pyenv/versions/{{ lookup('ansible.builtin.env', 'python_major_version') }}\
      /envs/python{{ lookup('ansible.builtin.env', 'python_major_version') }}"
